# Generated by Django 2.1.3 on 2018-12-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('image_memetor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
