# Generated by Django 2.1.3 on 2019-01-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('image_memetor', '0002_auto_20181204_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/memes/')),
            ],
        ),
    ]
